[package]
name = "dash"
version = "0.1.0"
authors = ["byte[] <byteslice@airmail.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
